name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Android SDK 
      uses: android-actions/setup-android@v2 
      with: 
       api-level: 30 
      # 其他有效参数 
    - name: Install NDK 
      run: 
        |
        wget https://dl.google.com/android/repository/android-ndk-r25b-linux.zip 
        unzip android-ndk-r25b-linux.zip -d $HOME/android-ndk
        export ANDROID_NDK_HOME=$
      
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.20'

    - name: Install gomobile
      run: |
        go install golang.org/x/mobile/cmd/gomobile@latest
        gomobile init

    - name: Build
      run: |
        export GOOS=android
        export GOARCH=arm64
        gomobile bind -target=android .
        mkdir -p output
        cp *.aar output/

    - name: Upload AAR
      uses: actions/upload-artifact@v4
      with:
        name: my-go-library
        path: output/*.aar






