name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Install Android SDK 
      uses: android-actions/setup-android@v2
      with:
         sdk-version: 'commandlinetools-linux-8512546_latest' 
         ndk-version: '25.2.9519653' # 使用支持的 NDK 版本 


    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.20'

    - name: Build
      run: go build -v -o main ./...

    - name: Run
      run: ./main

    - name: Install gomobile
      run: |
        go install golang.org/x/mobile/cmd/gomobile@latest
        gomobile init

    - name: Build AAR
      run: |
        gomobile bind -target=android .
        mkdir -p output
        cp *.aar output/

    - name: Upload AAR
      uses: actions/upload-artifact@v4
      with:
        Name: my-go-library
        path: output/*.aar
